SEED = 58
DATA_ROOT = "Kvasir-SEG"
SAM_CHECKPOINT = "sam_vit_b_01ec64.pth"
OUTPUT_DIR = "outputs"
CHECKPOINT_NAME = "model.pth"

TRAIN_RATIO = 0.8
VAL_RATIO = 0.1
TEST_RATIO = 1 - TRAIN_RATIO - VAL_RATIO

NUM_EPOCHS = 10
LEARNING_RATE = 0.0001
WEIGHT_DECAY = 0.0001